### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by oliviervd** [StadGent/node_service_adlib-backend#102]
when running the service, this Error occurs. 

`node:internal/crypto/cipher:122    this[kHandle].initiv(cipher, credential, iv, authTagLength);                  ^Error: error:0308010C:digital envelope routines::unsupported    at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)    at new Cipheriv (node:internal/crypto/cipher:249:3)    at Object.createCipheriv (node:crypto:148:10)    at encrypt (/Users/huynslol/IdeaProjects/node_service_adlib-backend/node_modules/httpntlm/ntlm.js:276:20)    at create_LM_hashed_password_v1 (/Users/huynslol/IdeaProjects/node_service_adlib-backend/node_modules/httpntlm/ntlm.js:280:27)    at Object.createType3Message (/Users/huynslol/IdeaProjects/node_service_adlib-backend/node_modules/httpntlm/ntlm.js:181:70)    at sendType3Message (/Users/huynslol/IdeaProjects/node_service_adlib-backend/node_modules/httpntlm/httpntlm.js:77:23)    at Immediate.<anonymous> (/Users/huynslol/IdeaProjects/node_service_adlib-backend/node_modules/httpntlm/httpntlm.js:101:4)    at processImmediate (node:internal/timers:475:21)    at process.callbackTrampoline (node:internal/async_hooks:130:17) {  library: 'digital envelope routines',  reason: 'unsupported',  code: 'ERR_OSSL_EVP_UNSUPPORTED'}`

seems to be related to the bump to Node 18.x --> https://github.com/StadGent/node_service_adlib-backend/pull/97
(https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)

setting `$env:NODE_OPTIONS = "--openssl-legacy-provider"`
seems to fix the issue. However this option results in possible security issues. 

other option would be to downgrade node to current LTS version.

**Comment by oliviervd** [comment]
see; https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by MPParsley** [comment]
This is a [known issue with http-ntlm](https://github.com/SamDecrock/node-http-ntlm/issues/103) and will be solved in #97.
