### ISSUE TITLE
Avoid duplicates

### ISSUE THREAD

**Issue by MPParsley** [StadGent/node_service_adlib-backend#12]
Momenteel kan het voorkomen dat dezelfde data meermaals bewaard wordt, o.a. in dit scenario: #11 
Te bekijken of we dit kunnen vermijden met een upsert.

**Comment by aatauil** [comment]
Ik heb al gekeken en sequelize heeft support voor upsert dus `create` hier: https://github.com/StadGent/node_service_adlib-backend/blob/87279535b2916f35840ac914a9e1fcde546240b7/src/lib/utils.js#L16 zou naar upsert kunnen worden gewijzigd. Maar ik weet niet of dit de oplossing zal zijn. Upsert kijkt normaal naar de primary key en in dit geval is gebruiken we auto_increment dus vermoed ik dat deze niet zal worden gedetecteerd als duplicate. We zullen een andere primary key moeten hebben die wel altijd uniek is? Priref misschien? Heb zelf nog nooit upsert gebruikt en ben hiertegen gelopen wanneer ik dit zelf wilde oplossen

**Comment by MPParsley** [comment]
Duplicates zijn opgelost in https://github.com/StadGent/node_service_adlib-backend/commit/70d5084c8ccc69424536fe9c33dfe446df57226f
