### ISSUE TITLE
Map Identificator fields in DMG objecten

### ISSUE THREAD

**Issue by pietercolpaert** [StadGent/node_service_adlib-backend#24]
Object.Identifcator ontbreekt nog in de client. Deze wordt wel getoond in gepubliceerde LDES.

https://apidg.gent.be/opendata/adlib2eventstream/v1/dmg/objecten?generatedAtTime=2021-08-15T01:56:04.152Z

Original issue: https://github.com/TREEcg/event-stream-client/issues/21

**Comment by brechtvdv** [comment]
Wordt hier gefixet: https://github.com/StadGent/node_service_adlib-backend/blob/691aacc737787fc1552b07d25e2752f6006b5406/src/lib/mappers/objectMapper.js#L14
